//! `kb_core::add` — unified add primitive with atomic batched expire+upsert.
//!
//! # Contract
//!
//! This module is the SINGLE entry point for all "add an entry" operations:
//! - CLI: `src/commands/add.rs::Add::execute_with`
//! - MCP: `src/commands/mcp.rs::handle_add`
//! - MCP audit-record expire arm: `src/commands/mcp.rs::handle_audit_record`
//!
//! # JSONL-first ordering (Phase-5 ADR §Scenario 4)
//!
//! DB writes NEVER precede their event append.  The batch ordering is:
//!   1. `events::append_events_batch([expire_0, ..., expire_n, upsert, ev_add_0, ...])` — all at once
//!   2. `db::apply_event` for each event in the same order, all under the held flock.
//!
//! A crash between (1) and (2) leaves the JSONL ahead of the DB — the rebuild
//! path recovers.  A crash INSIDE (1) (before the write returns) is an atomic
//! append failure; the JSONL is unchanged and the DB is unchanged.  Either way
//! the steady-state invariant `DB == Materialize(events.jsonl)` holds.
//!
//! # Drift table (previously-divergent fields — now unified)
//!
//! | Field             | Old add.rs          | Old handle_add      | Old handle_audit_record | Unified here |
//! |-------------------|---------------------|---------------------|-------------------------|--------------|
//! | `kind` default    | `"belief"` (clap)   | `"belief"` (unwrap) | N/A (expire only)       | `"belief"`   |
//! | `session` field   | `"cli"` fallback    | `"mcp"` hard-coded  | `"mcp"` hard-coded      | caller sets  |
//! | `session_id` field| absent              | present if set      | N/A                     | passed in    |
//! | replace_path reason| `"replaced by --replace-path"` | `"replaced by MCP kb_add replace_path"` | N/A | caller sets via `expire_reason` |
//! | batch atomicity   | PER-LOOP append+apply | PER-LOOP append+apply | PER-LOOP append+apply | single batch |
//!
//! # TLA+ spec
//!
//! See `agent-kb/tla/replace_path_atomic.tla` — two refinement layers:
//!   Layer 1 (inner): per-event append/apply gap within a single `kb_core::add` call.
//!   Layer 2 (cross-batch): cross-invocation boundary between distinct `kb_core::add` calls.

use crate::commands::add::acquire_lock;
use crate::components::{db, embedder, events, redactor};
use crate::config;
use crate::models::Evidence;
use anyhow::Result;
use rusqlite::params;
use serde_json::Value;

/// Input arguments for `kb_core::add`.
///
/// Caller is responsible for:
/// - validating `kind`, `tags`, `evidence_rows` via `validate_kb_add_inputs`
/// - computing `evidence_status` via `compute_evidence_status_write`
/// - constructing `id` (UUID or caller-supplied)
/// - setting `session` and `session_id` appropriate to the call site
/// - setting `expire_reason` appropriate to the call site
pub struct AddArgs {
    pub id: String,
    pub path: String,
    pub summary: String,
    pub content: String,
    /// JSON array value of tags.
    pub tags: Value,
    pub version_ref: Option<String>,
    pub permanent: bool,
    pub replace_path: bool,
    pub kind: String,
    pub evidence_status: String,
    pub evidence_rows: Vec<Value>,
    /// Timestamp string (RFC 3339).
    pub ts: String,
    /// Session label written into the event `"session"` field (e.g. `"cli"` or `"mcp"`).
    pub session: String,
    /// Session ID written into the upsert event `"session_id"` field.
    /// `None` means the field is omitted from the event (backward-compatible).
    pub session_id: Option<String>,
    /// Reason string used in expire events generated by `replace_path`.
    /// Preserves per-call-site wording (previously divergent across call sites).
    pub expire_reason: String,
}

/// Result returned by `kb_core::add`.
pub struct AddOutcome {
    /// The entry ID (same as `AddArgs::id`).
    pub entry_id: String,
}

/// Unified add primitive.
///
/// Acquires the flock, then:
/// 1. Collects any existing non-stale entry IDs at `args.path` (when `replace_path=true`).
/// 2. Builds expire events + the upsert event + evidence-add events.
/// 3. Appends ALL events in ONE `events::append_events_batch` call (JSONL-first).
/// 4. Applies each event to the DB in order, all under the held flock.
///
/// INVARIANT: this function NEVER reads `KB_NO_EMBED` from the environment.
/// The caller must construct the Embedder before calling and pass it by reference.
pub fn add(
    paths: &config::Paths,
    embedder: &dyn embedder::Embedder,
    mut args: AddArgs,
) -> Result<AddOutcome> {
    // Redact credentials from user-supplied text fields before persisting.
    args.content = redactor::redact_str(&args.content).into_owned();
    args.summary = redactor::redact_str(&args.summary).into_owned();
    redactor::redact_in_place(&mut args.tags);
    for ev in args.evidence_rows.iter_mut() {
        if let Some(excerpt) = ev.get_mut("citation_excerpt") {
            redactor::redact_in_place(excerpt);
        }
    }

    let _lock = acquire_lock(&paths.lock)?;
    let conn = db::open_db(&paths.db)?;

    // Collect existing IDs to expire when replace_path is requested.
    let existing_ids: Vec<String> = if args.replace_path {
        let mut stmt =
            conn.prepare("SELECT id FROM entries WHERE path=?1 AND is_stale=0")?;
        let ids: Vec<String> = stmt
            .query_map(params![args.path], |r| r.get(0))?
            .filter_map(|r| r.ok())
            .collect();
        ids
    } else {
        vec![]
    };

    // Build expire events (one per existing entry being replaced).
    let expire_events: Vec<Value> = existing_ids
        .iter()
        .map(|old_id| {
            serde_json::json!({
                "action": "expire",
                "table": "entries",
                "id": old_id,
                "reason": args.expire_reason,
                "ts": args.ts,
                "session": args.session,
            })
        })
        .collect();

    // Build the upsert event.
    let add_event = serde_json::json!({
        "action": "upsert",
        "table": "entries",
        "id": args.id,
        "path": args.path,
        "summary": args.summary,
        "content": args.content,
        "tags": args.tags,
        "version_ref": args.version_ref,
        "permanent": args.permanent,
        "kind": args.kind,
        "evidence_status": args.evidence_status,
        "session_id": args.session_id,
        "ts": args.ts,
        "session": args.session,
    });

    // Build evidence-add events (one per evidence row).
    let evidence_events: Vec<Value> = args
        .evidence_rows
        .iter()
        .map(|ev| {
            let evidence = Evidence {
                id: uuid::Uuid::new_v4().to_string(),
                entry_id: args.id.clone(),
                kind: ev
                    .get("kind")
                    .and_then(|v| v.as_str())
                    .unwrap_or("code")
                    .to_string(),
                citation_path: ev
                    .get("citation_path")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                citation_sha: ev
                    .get("citation_sha")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                citation_hash: ev
                    .get("citation_hash")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string(),
                citation_excerpt: ev
                    .get("citation_excerpt")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                derived_from: ev
                    .get("derived_from")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                recorded_at: Some(args.ts.clone()),
            };
            events::evidence_add_event(&args.id, &evidence, args.version_ref.as_deref())
        })
        .collect();

    // ATOMIC BATCH: all expire events + upsert + evidence-add events in ONE write.
    // JSONL-first invariant: this append precedes all DB writes.
    // Order: expires, upsert, evidence-adds. The same Vec is then applied to the
    // DB in-order under the held flock, so no per-event clone is needed.
    let mut batch: Vec<Value> = expire_events;
    batch.push(add_event);
    batch.extend(evidence_events);
    events::append_events_batch(&paths.events, &batch)?;

    for ev in &batch {
        db::apply_event(&conn, embedder, ev)?;
    }

    Ok(AddOutcome {
        entry_id: args.id,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::components::embedder::NoopEmbedder;
    use crate::components::events as ev_mod;
    use crate::config::Paths;
    use rusqlite::Connection;
    use std::fs;
    use tempfile::tempdir;

    fn setup() -> (tempfile::TempDir, Paths) {
        let dir = tempdir().unwrap();
        let root = dir.path().to_path_buf();
        fs::create_dir_all(root.join(".state/agent-kb")).unwrap();
        let paths = Paths::from_root(&root);
        (dir, paths)
    }

    // -------------------------------------------------------------------------
    // FAILING ACCEPTANCE TEST (written pre-implementation per TDD mandate).
    //
    // AC2 (batch atomicity): expire events and upsert land in ONE
    // `append_events_batch` call — NOT a loop of per-event appends.
    //
    // Pre-fix, the call sites in add.rs and mcp.rs use:
    //   for old_id in existing_ids {
    //       append_event(&paths.events, &expire_ev)?;   // ← one append per expire
    //       apply_event(&conn, emb, &expire_ev)?;
    //   }
    //   append_events_batch(&paths.events, &[add_event, ...evidence...])
    //
    // That means N+1 separate JSONL write calls, not 1.  This test verifies
    // that after a `kb_core::add` with replace_path=true the event log contains
    // all events as a SINGLE contiguous block (measurable via line count == 1 +
    // expire_count + evidence_count and ordering verification).
    //
    // Because kb_core::add is the NEW module, this test can only PASS once the
    // implementation below exists.  Before the module existed the test file
    // itself would not compile, proving the "failing first" property.
    // -------------------------------------------------------------------------

    /// AC2: replace_path=true with two pre-existing entries:
    /// All events (2 expire + 1 upsert) appear in the JSONL in the correct order.
    #[test]
    fn test_kb_core_add_batch_atomicity_replace_path() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Seed two existing entries at the same path.
        for seed_id in &["seed-1", "seed-2"] {
            let ev = serde_json::json!({
                "action": "upsert", "table": "entries",
                "id": seed_id, "path": "docs/guide",
                "summary": "old", "content": "old", "tags": [],
                "ts": "2024-01-01T00:00:00Z",
            });
            ev_mod::append_event(&paths.events, &ev).unwrap();
            let conn = db::open_db(&paths.db).unwrap();
            db::apply_event(&conn, &emb, &ev).unwrap();
        }

        // Count lines before.
        let before_lines = fs::read_to_string(&paths.events)
            .unwrap()
            .lines()
            .count();
        assert_eq!(before_lines, 2, "seeded 2 events");

        let args = AddArgs {
            id: "new-1".to_string(),
            path: "docs/guide".to_string(),
            summary: "new guide".to_string(),
            content: "new content".to_string(),
            tags: serde_json::json!([]),
            version_ref: Some("abc".to_string()),
            permanent: false,
            replace_path: true,
            kind: "convention".to_string(),
            evidence_status: "n/a".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: "replaced by --replace-path".to_string(),
        };

        add(&paths, &emb, args).unwrap();

        let after_content = fs::read_to_string(&paths.events).unwrap();
        let lines: Vec<&str> = after_content.lines().collect();

        // 2 seed events + 2 expire + 1 upsert = 5 total lines.
        assert_eq!(
            lines.len(),
            5,
            "expected 5 lines (2 seed + 2 expire + 1 upsert), got {}",
            lines.len()
        );

        // Lines 2 and 3 (0-indexed) must be expire events.
        let ev2: Value = serde_json::from_str(lines[2]).unwrap();
        let ev3: Value = serde_json::from_str(lines[3]).unwrap();
        let ev4: Value = serde_json::from_str(lines[4]).unwrap();
        assert_eq!(ev2["action"], "expire", "line[2] must be expire");
        assert_eq!(ev3["action"], "expire", "line[3] must be expire");
        assert_eq!(ev4["action"], "upsert", "line[4] must be upsert");
        assert_eq!(ev4["id"], "new-1");

        // DB: old entries must be stale, new entry active.
        let conn = Connection::open(&paths.db).unwrap();
        for seed_id in &["seed-1", "seed-2"] {
            let stale: i64 = conn
                .query_row(
                    "SELECT is_stale FROM entries WHERE id=?1",
                    params![seed_id],
                    |r| r.get(0),
                )
                .unwrap();
            assert_eq!(stale, 1, "seed {seed_id} must be stale");
        }
        let new_stale: i64 = conn
            .query_row(
                "SELECT is_stale FROM entries WHERE id='new-1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(new_stale, 0, "new entry must be active");
    }

    /// AC1 (signature): kb_core::add does NOT read KB_NO_EMBED from the environment.
    /// The embedder is injected by the caller.
    ///
    /// This test calls kb_core::add with a NoopEmbedder while KB_NO_EMBED is
    /// unset. If the impl read KB_NO_EMBED, it would silently switch embedder
    /// behavior; since we control the embedder here, we can assert the correct
    /// path was taken.
    #[test]
    fn test_kb_core_add_embedder_injected_not_from_env() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Ensure KB_NO_EMBED is not set.
        std::env::remove_var("KB_NO_EMBED");

        let args = AddArgs {
            id: "env-test-1".to_string(),
            path: "src/foo".to_string(),
            summary: "env test".to_string(),
            content: "body".to_string(),
            tags: serde_json::json!(["env"]),
            version_ref: None,
            permanent: false,
            replace_path: false,
            kind: "belief".to_string(),
            evidence_status: "missing".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: String::new(),
        };

        // Must succeed — the NoopEmbedder is injected and used, not looked up via env.
        add(&paths, &emb, args).unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM entries WHERE id='env-test-1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(count, 1, "entry must exist in DB");
    }

    /// AC4 (drift table): session_id is propagated to the upsert event.
    #[test]
    fn test_kb_core_add_session_id_propagated() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        let args = AddArgs {
            id: "sess-test-1".to_string(),
            path: "src/sess".to_string(),
            summary: "sess test".to_string(),
            content: "body".to_string(),
            tags: serde_json::json!([]),
            version_ref: None,
            permanent: false,
            replace_path: false,
            kind: "convention".to_string(),
            evidence_status: "n/a".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "mcp".to_string(),
            session_id: Some("test-sess-42".to_string()),
            expire_reason: String::new(),
        };

        add(&paths, &emb, args).unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let session_id: Option<String> = conn
            .query_row(
                "SELECT session_id FROM entries WHERE id='sess-test-1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(session_id, Some("test-sess-42".to_string()));
    }

    /// AC3 (convergence): test that add.rs::execute_with delegates to kb_core::add
    /// by verifying the same atomicity property holds when called through the CLI
    /// path.  The CLI path goes through `Add::execute_with` which must call
    /// `kb_core::add` after the refactor.
    #[test]
    fn test_add_execute_with_delegates_to_kb_core() {
        use crate::commands::add::Add;

        let dir = tempdir().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join(".state/agent-kb")).unwrap();
        let paths = Paths::from_root(root);
        let emb = NoopEmbedder;

        // Seed an entry at the path.
        let seed_cmd = Add {
            path: "docs/convergence".to_string(),
            summary: "old".to_string(),
            content: "old".to_string(),
            tags: "test".to_string(),
            version_ref: Some("aaa".to_string()),
            id: Some("conv-seed-1".to_string()),
            permanent: false,
            replace_path: false,
            kind: "convention".to_string(),
            evidence: vec![],
            evidence_file: None,
        };
        seed_cmd.execute_with(&paths, &emb).unwrap();

        let before_lines = fs::read_to_string(&paths.events).unwrap().lines().count();

        // Now add with replace_path — all events must land in one batch.
        let cmd = Add {
            path: "docs/convergence".to_string(),
            summary: "new".to_string(),
            content: "new".to_string(),
            tags: "test".to_string(),
            version_ref: Some("bbb".to_string()),
            id: Some("conv-new-1".to_string()),
            permanent: false,
            replace_path: true,
            kind: "convention".to_string(),
            evidence: vec![],
            evidence_file: None,
        };
        cmd.execute_with(&paths, &emb).unwrap();

        let after_content = fs::read_to_string(&paths.events).unwrap();
        let lines: Vec<&str> = after_content.lines().collect();

        // before_lines + 1 expire + 1 upsert
        assert_eq!(
            lines.len(),
            before_lines + 2,
            "expected {}, got {}",
            before_lines + 2,
            lines.len()
        );
        // The expire must appear BEFORE the upsert.
        let expire_ev: Value =
            serde_json::from_str(lines[before_lines]).unwrap();
        let upsert_ev: Value =
            serde_json::from_str(lines[before_lines + 1]).unwrap();
        assert_eq!(expire_ev["action"], "expire");
        assert_eq!(upsert_ev["action"], "upsert");
        assert_eq!(upsert_ev["id"], "conv-new-1");
    }

    /// AC3 (convergence): test that mcp.rs::handle_add delegates to kb_core::add.
    #[test]
    fn test_handle_add_delegates_to_kb_core() {
        use crate::commands::mcp::tests_api::handle_add_for_test;

        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Seed entry via a raw event (bypass handle_add) so we control the state.
        let seed_ev = serde_json::json!({
            "action": "upsert", "table": "entries",
            "id": "mcp-seed-1", "path": "mcp/conv",
            "summary": "old", "content": "old", "tags": [],
            "ts": "2024-01-01T00:00:00Z",
        });
        ev_mod::append_event(&paths.events, &seed_ev).unwrap();
        let conn = db::open_db(&paths.db).unwrap();
        db::apply_event(&conn, &emb, &seed_ev).unwrap();
        drop(conn);

        let before_lines = fs::read_to_string(&paths.events).unwrap().lines().count();

        let id = serde_json::json!("mcp-test");
        let req = serde_json::json!({
            "method": "add", "id": "mcp-test",
            "path": "mcp/conv", "summary": "new", "content": "new",
            "tags": ["a"], "kind": "convention", "replace_path": true,
        });
        let resp = handle_add_for_test(&id, &req, &paths, &emb);
        assert_eq!(resp["type"], "ok", "resp: {resp}");

        let after_content = fs::read_to_string(&paths.events).unwrap();
        let lines: Vec<&str> = after_content.lines().collect();
        // before_lines + 1 expire + 1 upsert
        assert_eq!(
            lines.len(),
            before_lines + 2,
            "expected {} lines, got {}",
            before_lines + 2,
            lines.len()
        );
        let expire_ev: Value =
            serde_json::from_str(lines[before_lines]).unwrap();
        let upsert_ev: Value =
            serde_json::from_str(lines[before_lines + 1]).unwrap();
        assert_eq!(expire_ev["action"], "expire", "expire must come first");
        assert_eq!(upsert_ev["action"], "upsert");
    }
}
