//! `kb_core::add` — unified add primitive with atomic batched expire+upsert.
//!
//! # Contract
//!
//! This module is the SINGLE entry point for all "add an entry" operations:
//! - CLI: `src/commands/add.rs::Add::execute_with`
//! - MCP: `src/commands/mcp.rs::handle_add`
//! - MCP audit-record expire arm: `src/commands/mcp.rs::handle_audit_record`
//!
//! # JSONL-first ordering (Phase-5 ADR §Scenario 4)
//!
//! DB writes NEVER precede their event append.  The batch ordering is:
//!   1. `events::append_events_batch([expire_0, ..., expire_n, upsert, ev_add_0, ...])` — all at once
//!   2. `db::apply_event` for each event in the same order, all under the held flock.
//!
//! A crash between (1) and (2) leaves the JSONL ahead of the DB — the rebuild
//! path recovers.  A crash INSIDE (1) (before the write returns) is an atomic
//! append failure; the JSONL is unchanged and the DB is unchanged.  Either way
//! the steady-state invariant `DB == Materialize(events.jsonl)` holds.
//!
//! # Drift table (previously-divergent fields — now unified)
//!
//! | Field             | Old add.rs          | Old handle_add      | Old handle_audit_record | Unified here |
//! |-------------------|---------------------|---------------------|-------------------------|--------------|
//! | `kind` default    | `"belief"` (clap)   | `"belief"` (unwrap) | N/A (expire only)       | `"belief"`   |
//! | `session` field   | `"cli"` fallback    | `"mcp"` hard-coded  | `"mcp"` hard-coded      | caller sets  |
//! | `session_id` field| absent              | present if set      | N/A                     | passed in    |
//! | replace_path reason| `"replaced by --replace-path"` | `"replaced by MCP kb_add replace_path"` | N/A | caller sets via `expire_reason` |
//! | batch atomicity   | PER-LOOP append+apply | PER-LOOP append+apply | PER-LOOP append+apply | single batch |
//!
//! # TLA+ spec
//!
//! See `.state/agent-kb/tla/InnerGap.tla` and
//! `.state/agent-kb/tla/CrossBatch.tla` — two refinement layers:
//!   Layer 1 (inner): per-event append/apply gap within a single `kb_core::add` call.
//!   Layer 2 (cross-batch): cross-invocation boundary between distinct `kb_core::add` calls.

#![allow(deprecated)] // db::open_db (ADR-1) — remaining call sites migrate in C2/L1b, L2, L3, L1c
use crate::commands::add::{acquire_lock, Lock};
use crate::crash_sim::{kill_point, KillPoint};
use crate::components::verification::{compute_citation_hash, parse_citation_path};
use crate::components::{db, embedder, events, redactor};
use crate::config;
use crate::models::Evidence;
use anyhow::{Context, Result};
use rusqlite::{params, Connection};
use serde_json::Value;
use std::collections::HashMap;

#[cfg(test)]
use std::cell::Cell;

// Thread-local, not a global static: memoization happens per-add on one
// thread, and cargo runs tests in parallel threads, so a global counter
// picks up concurrent tests' resolutions inside this test's window
// (cross-test race, found when the storage-reliability tests shifted
// scheduling). A thread-local counter measures only this test's own calls.
#[cfg(test)]
thread_local! {
    static CITATION_HASH_RESOLUTION_CALLS: Cell<usize> = const { Cell::new(0) };
}

fn resolve_citation_hash(
    repo_root: &std::path::Path,
    file_rel: &str,
    range: Option<(usize, usize)>,
) -> Result<String> {
    #[cfg(test)]
    CITATION_HASH_RESOLUTION_CALLS.with(|c| c.set(c.get() + 1));

    compute_citation_hash(repo_root, file_rel, range)
}

/// Input arguments for `kb_core::add`.
///
/// Caller is responsible for:
/// - validating `kind`, `tags`, `evidence_rows` via `validate_kb_add_inputs`
/// - computing `evidence_status` via `compute_evidence_status_write`
/// - constructing `id` (UUID or caller-supplied)
/// - setting `session` and `session_id` appropriate to the call site
/// - setting `expire_reason` appropriate to the call site
pub struct AddArgs {
    pub id: String,
    pub path: String,
    pub summary: String,
    pub content: String,
    /// JSON array value of tags.
    pub tags: Value,
    pub version_ref: Option<String>,
    pub permanent: bool,
    pub replace_path: bool,
    pub kind: String,
    pub evidence_status: String,
    pub evidence_rows: Vec<Value>,
    /// Timestamp string (RFC 3339).
    pub ts: String,
    /// Session label written into the event `"session"` field (e.g. `"cli"` or `"mcp"`).
    pub session: String,
    /// Session ID written into the upsert event `"session_id"` field.
    /// `None` means the field is omitted from the event (backward-compatible).
    pub session_id: Option<String>,
    /// Reason string used in expire events generated by `replace_path`.
    /// Preserves per-call-site wording (previously divergent across call sites).
    pub expire_reason: String,
    /// Cosine cutoff for the near-duplicate probe. `None` disables the probe
    /// (internal callers: rebuild, digest, compress — re-adding known content).
    pub dedup_cutoff: Option<f32>,
    /// Cue anchors: agent-supplied semantic entry points, pattern
    /// "[Main Entity] + [Key Aspect]" (Memora). Ride the upsert event and are
    /// stored as embedded rows in the `cues` table. Empty = no cues field.
    pub cues: Vec<String>,
}

/// A live entry semantically close to the one being added.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SimilarEntry {
    pub id: String,
    pub path: String,
    pub summary: String,
    pub score: f32,
}

/// Result returned by `kb_core::add`.
#[derive(Debug)]
pub struct AddOutcome {
    /// The entry ID (same as `AddArgs::id`).
    pub entry_id: String,
    /// Live entries with embedding cosine >= `dedup_cutoff` (empty when the
    /// probe is disabled). The add is NOT blocked — the calling agent decides
    /// whether to merge, expire, or keep both.
    pub similar_existing: Vec<SimilarEntry>,
}

/// Unified add primitive: acquires the write lock, opens for mutation, and
/// delegates to [`add_locked`].
///
/// A thin wrapper on purpose. Callers that already hold the lock — a locked
/// batch import, any future multi-entry write path — must call [`add_locked`]
/// directly; calling this one would re-acquire the flock and, before the
/// re-entrancy registry existed, deadlock on itself (ADR-1).
///
/// INVARIANT: this function NEVER reads `KB_NO_EMBED` from the environment.
/// The caller must construct the Embedder before calling and pass it by reference.
pub fn add(
    paths: &config::Paths,
    embedder: &dyn embedder::Embedder,
    args: AddArgs,
) -> Result<AddOutcome> {
    let lock = acquire_lock(&paths.lock)?;
    let conn = db::open_rw(paths, &lock)?;
    add_locked(&lock, &conn, paths, embedder, args)
}

/// The add logic, for a caller that already holds this repository's write lock.
///
/// 1. Validates, redacts, and caps the inputs.
/// 2. Collects any existing non-stale entry IDs at `args.path` (when `replace_path=true`).
/// 3. Builds expire events + the upsert event + evidence-add events.
/// 4. Appends ALL events in ONE `events::append_events_batch` call (JSONL-first).
/// 5. Applies each event to the DB in order, all under the caller's flock.
///
/// Input preparation runs inside the critical section rather than ahead of it,
/// which is a deliberate trade: one code path for both entry points is worth
/// more than the few milliseconds of citation hashing it adds to the lock hold.
///
/// `lock` is proof, not a resource: it is checked against `paths.lock` and never
/// released here — the caller's guard still owns it.
pub fn add_locked(
    lock: &Lock,
    conn: &Connection,
    paths: &config::Paths,
    embedder: &dyn embedder::Embedder,
    mut args: AddArgs,
) -> Result<AddOutcome> {
    // Redundant but intentional: open_rw canonicalized paths.lock before it
    // opened `conn`; re-checking here keeps add_locked self-contained for any
    // future caller handed a live lock + connection pair from elsewhere.
    let expected_lock = std::fs::canonicalize(&paths.lock).with_context(|| {
        format!(
            "canonicalize write lock {} (add_locked requires a live lock guard)",
            paths.lock.display()
        )
    })?;
    if lock.path() != expected_lock {
        anyhow::bail!(
            "add_locked: the supplied lock guards {}, but this repository's write lock is {}",
            lock.path().display(),
            expected_lock.display()
        );
    }

    let repo_root = paths
        .db
        .parent()
        .and_then(|p| p.parent())
        .and_then(|p| p.parent())
        .ok_or_else(|| anyhow::anyhow!("cannot determine repository root from KB database path"))?;

    // Normalize path-only evidence before constructing any events. Explicit
    // assertions are authoritative and are never replaced, even when wrong.
    let mut resolved_hashes_by_path: HashMap<String, String> = HashMap::new();
    for evidence in &mut args.evidence_rows {
        let hash_missing = evidence
            .get("citation_hash")
            .and_then(Value::as_str)
            .map(str::is_empty)
            .unwrap_or(true);
        if !hash_missing {
            continue;
        }
        let citation_path = evidence
            .get("citation_path")
            .and_then(Value::as_str)
            .filter(|path| !path.is_empty())
            .ok_or_else(|| {
                anyhow::anyhow!("evidence row missing required citation_path or citation_hash")
            })?;
        let (file_rel, range) = parse_citation_path(citation_path)
            .map_err(|error| anyhow::anyhow!("resolve citation_path {citation_path:?}: {error}"))?;
        let citation_hash = if let Some(existing) = resolved_hashes_by_path.get(citation_path) {
            existing.clone()
        } else {
            let resolved = resolve_citation_hash(repo_root, file_rel, range).map_err(|error| {
                anyhow::anyhow!("resolve citation_path {citation_path:?}: {error}")
            })?;
            resolved_hashes_by_path.insert(citation_path.to_string(), resolved.clone());
            resolved
        };
        let object = evidence
            .as_object_mut()
            .ok_or_else(|| anyhow::anyhow!("evidence row must be a JSON object"))?;
        object.insert("citation_hash".to_string(), Value::String(citation_hash));
        if object.get("citation_sha").map_or(true, Value::is_null) {
            if let Some(head) = config::git_head_sha() {
                object.insert("citation_sha".to_string(), Value::String(head));
            }
        }
    }

    // Resource caps for cue anchors (mirrors evidence-row caps): bounded count
    // and length keep the embed cost and cue-table growth per add bounded.
    const MAX_CUES: usize = 8;
    const MAX_CUE_CHARS: usize = 120;
    if args.cues.len() > MAX_CUES {
        anyhow::bail!("too many cues: {} (max {MAX_CUES})", args.cues.len());
    }
    if args.cues.iter().any(|c| c.chars().count() > MAX_CUE_CHARS) {
        anyhow::bail!("cue exceeds {MAX_CUE_CHARS} chars");
    }

    // Redact credentials from user-supplied text fields before persisting.
    args.content = redactor::redact_str(&args.content).into_owned();
    args.summary = redactor::redact_str(&args.summary).into_owned();
    for cue in args.cues.iter_mut() {
        *cue = redactor::redact_str(cue).into_owned();
    }
    redactor::redact_in_place(&mut args.tags);
    for ev in args.evidence_rows.iter_mut() {
        if let Some(excerpt) = ev.get_mut("citation_excerpt") {
            redactor::redact_in_place(excerpt);
        }
    }

    // Entry field caps — validated on the REDACTED values (redaction markers
    // can change length) so the schema CHECK can never fire mid-batch.
    // Rejecting here gives a clear error; apply_event's clamp is for legacy
    // pre-cap events only, never for new writes.
    if args.summary.chars().count() > db::MAX_SUMMARY_CHARS {
        anyhow::bail!(
            "summary exceeds {} chars ({})",
            db::MAX_SUMMARY_CHARS,
            args.summary.chars().count()
        );
    }
    if args.content.chars().count() > db::MAX_ENTRY_CONTENT_CHARS {
        anyhow::bail!(
            "content exceeds {} chars ({}) — split the entry or use kb ingest",
            db::MAX_ENTRY_CONTENT_CHARS,
            args.content.chars().count()
        );
    }

    // Near-duplicate probe (Memora pickup .5): semantic-only search for live
    // entries close to the incoming one. Runs BEFORE the new entry is written
    // so it can never self-match. Best-effort: a probe failure must not block
    // the add.
    let similar_existing: Vec<SimilarEntry> = match args.dedup_cutoff {
        Some(cutoff) if !embedder.is_noop() => {
            let probe_text = db::entry_embed_text(
                db::EmbedTextMode::from_env(),
                &args.path,
                &args.summary,
                &args.content,
                &args.tags.to_string(),
            );
            let opts = db::SearchOptions {
                limit: 5,
                do_fts: false,
                do_semantic: true,
                path_prefix: None,
                tag_filter: None,
                inline_verify_k: 0,
                repo_root: None,
                verify_pool_size: None,
                recency_lambda: 0.0,
                mmr_lambda: 0.0,
            };
            match db::search_entries(&conn, embedder, &probe_text, &opts) {
                Ok(results) => results
                    .into_iter()
                    .filter(|r| r.score >= cutoff)
                    .filter(|r| r.id != args.id)
                    // replace_path expires same-path entries in this very call —
                    // reporting them as duplicates would be noise.
                    .filter(|r| !(args.replace_path && r.path == args.path))
                    .map(|r| SimilarEntry {
                        id: r.id,
                        path: r.path,
                        summary: r.summary,
                        score: r.score,
                    })
                    .collect(),
                Err(e) => {
                    eprintln!("warn: dedup probe failed (add proceeds): {e}");
                    vec![]
                }
            }
        }
        _ => vec![],
    };

    // Collect existing IDs to expire when replace_path is requested.
    let existing_ids: Vec<String> = if args.replace_path {
        let mut stmt = conn.prepare("SELECT id FROM entries WHERE path=?1 AND is_stale=0")?;
        let ids = stmt
            .query_map(params![args.path], |r| r.get(0))?
            .collect::<rusqlite::Result<Vec<String>>>()?;
        ids
    } else {
        vec![]
    };

    // Build expire events (one per existing entry being replaced).
    let expire_events: Vec<Value> = existing_ids
        .iter()
        .map(|old_id| {
            serde_json::json!({
                "action": "expire",
                "table": "entries",
                "id": old_id,
                "reason": args.expire_reason,
                "ts": args.ts,
                "session": args.session,
            })
        })
        .collect();

    // Build the upsert event. Cues ride the upsert event itself — there are
    // no separate cue events in the JSONL (.state/agent-kb/tla/CueBatch.tla).
    let mut add_event = serde_json::json!({
        "action": "upsert",
        "table": "entries",
        "id": args.id,
        "path": args.path,
        "summary": args.summary,
        "content": args.content,
        "tags": args.tags,
        "version_ref": args.version_ref,
        "permanent": args.permanent,
        "kind": args.kind,
        "evidence_status": args.evidence_status,
        "session_id": args.session_id,
        "ts": args.ts,
        "session": args.session,
    });
    if !args.cues.is_empty() {
        add_event["cues"] = serde_json::json!(args.cues);
    }

    // Build evidence-add events (one per evidence row).
    let evidence_events: Vec<Value> = args
        .evidence_rows
        .iter()
        .map(|ev| {
            let evidence = Evidence {
                id: uuid::Uuid::new_v4().to_string(),
                entry_id: args.id.clone(),
                kind: ev
                    .get("kind")
                    .and_then(|v| v.as_str())
                    .unwrap_or("code")
                    .to_string(),
                citation_path: ev
                    .get("citation_path")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                citation_sha: ev
                    .get("citation_sha")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                citation_hash: ev
                    .get("citation_hash")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string(),
                citation_excerpt: ev
                    .get("citation_excerpt")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                derived_from: ev
                    .get("derived_from")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                recorded_at: Some(args.ts.clone()),
            };
            events::evidence_add_event(&args.id, &evidence, args.version_ref.as_deref())
        })
        .collect();

    // ATOMIC BATCH: all expire events + upsert + evidence-add events in ONE write.
    // JSONL-first invariant: this append precedes all DB writes.
    // Order: expires, upsert, evidence-adds. The same Vec is then applied to the
    // DB in-order under the held flock, so no per-event clone is needed.
    let mut batch: Vec<Value> = expire_events;
    batch.push(add_event);
    batch.extend(evidence_events);
    events::append_events_batch(&paths.events, &batch)?;
    kill_point(KillPoint::AfterLogBatch);

    for ev in &batch {
        db::apply_event(&conn, embedder, ev)?;
    }

    if args.evidence_status == "missing"
        && matches!(args.kind.as_str(), "observation" | "belief" | "procedure")
    {
        eprintln!(
            "kb: warning: kind='{}' entry stored with evidence_status=missing — attach evidence via citation_path (server resolves sha/hash) or kb cite",
            args.kind
        );
    }

    Ok(AddOutcome {
        entry_id: args.id,
        similar_existing,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crash_sim::KillPoint;
    use crate::components::embedder::NoopEmbedder;
    use crate::components::events as ev_mod;
    use crate::config::Paths;
    use rusqlite::Connection;
    use std::fs;
    use std::process::Command;
    use tempfile::tempdir;

    fn setup() -> (tempfile::TempDir, Paths) {
        let dir = tempdir().unwrap();
        let root = dir.path().to_path_buf();
        fs::create_dir_all(root.join(".state/agent-kb")).unwrap();
        let paths = Paths::from_root(&root);
        (dir, paths)
    }

    fn evidence_args(evidence_rows: Vec<Value>) -> AddArgs {
        AddArgs {
            id: "evidence-test".to_string(),
            path: "tests/evidence".to_string(),
            summary: "evidence resolution".to_string(),
            content: "body".to_string(),
            tags: serde_json::json!([]),
            version_ref: None,
            permanent: false,
            replace_path: false,
            kind: "observation".to_string(),
            evidence_status: "present".to_string(),
            evidence_rows,
            ts: "2026-09-02T00:00:00Z".to_string(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: String::new(),
            dedup_cutoff: None,
            cues: vec![],
        }
    }

    fn crash_gap_args(entry_id: &str) -> AddArgs {
        AddArgs {
            id: entry_id.to_string(),
            path: "src/crash-gap.rs".to_string(),
            summary: "crash gap".to_string(),
            content: "persist me to the log first".to_string(),
            tags: serde_json::json!(["crash", "test"]),
            version_ref: Some("deadbeef".to_string()),
            permanent: false,
            replace_path: false,
            kind: "belief".to_string(),
            evidence_status: "missing".to_string(),
            evidence_rows: vec![],
            ts: "2026-09-04T00:00:00Z".to_string(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: String::new(),
            dedup_cutoff: None,
            cues: vec![],
        }
    }

    fn run_crash_gap_child() {
        let root = std::env::var("KB_CRASH_TEST_ROOT").unwrap();
        let paths = Paths::from_root(std::path::Path::new(&root));
        add(&paths, &NoopEmbedder, crash_gap_args("crash-gap-entry")).unwrap();
        panic!("child add returned without hitting the configured kill point");
    }

    fn load_test_evidence(conn: &Connection) -> Evidence {
        conn.query_row(
            "SELECT id, entry_id, kind, citation_path, citation_sha, citation_hash,
                    citation_excerpt, derived_from, recorded_at
             FROM evidence WHERE entry_id='evidence-test'",
            [],
            |row| {
                Ok(Evidence {
                    id: row.get(0)?,
                    entry_id: row.get(1)?,
                    kind: row.get(2)?,
                    citation_path: row.get(3)?,
                    citation_sha: row.get(4)?,
                    citation_hash: row.get(5)?,
                    citation_excerpt: row.get(6)?,
                    derived_from: row.get(7)?,
                    recorded_at: row.get(8)?,
                })
            },
        )
        .unwrap()
    }

    fn load_all_test_evidence(conn: &Connection) -> Vec<Evidence> {
        let mut stmt = conn
            .prepare(
                "SELECT id, entry_id, kind, citation_path, citation_sha, citation_hash,
                        citation_excerpt, derived_from, recorded_at
                 FROM evidence WHERE entry_id='evidence-test' ORDER BY rowid",
            )
            .unwrap();
        stmt.query_map([], |row| {
            Ok(Evidence {
                id: row.get(0)?,
                entry_id: row.get(1)?,
                kind: row.get(2)?,
                citation_path: row.get(3)?,
                citation_sha: row.get(4)?,
                citation_hash: row.get(5)?,
                citation_excerpt: row.get(6)?,
                derived_from: row.get(7)?,
                recorded_at: row.get(8)?,
            })
        })
        .unwrap()
        .map(|row| row.unwrap())
        .collect()
    }

    #[test]
    fn test_add_crash_after_log_batch_leaves_db_behind_log() {
        if std::env::var("KB_CRASH_TEST_CASE").ok().as_deref() == Some("after-log-batch") {
            run_crash_gap_child();
        }

        let (dir, paths) = setup();
        let entry_id = "crash-gap-entry";
        let status = Command::new(std::env::current_exe().unwrap())
            .arg("test_add_crash_after_log_batch_leaves_db_behind_log")
            .arg("--nocapture")
            .current_dir(dir.path())
            .env("KB_CRASH_TEST_CASE", "after-log-batch")
            .env("KB_CRASH_TEST_ROOT", dir.path())
            .env("KB_CRASH_AFTER", KillPoint::AfterLogBatch.to_string())
            .status()
            .unwrap();

        assert_eq!(
            status.code(),
            Some(137),
            "crash simulation should terminate the subprocess with exit code 137"
        );

        let events = fs::read_to_string(&paths.events).unwrap();
        assert!(
            events.contains(entry_id),
            "event log should contain the appended entry after the simulated crash"
        );

        if paths.db.exists() {
            let conn = Connection::open(&paths.db).unwrap();
            let rows: i64 = conn
                .query_row(
                    "SELECT COUNT(*) FROM entries WHERE id=?1",
                    [entry_id],
                    |row| row.get(0),
                )
                .unwrap();
            assert_eq!(rows, 0, "DB must not contain the entry after the crash");
        }
    }

    #[test]
    fn test_kb_core_add_resolves_bare_citation_path() {
        use crate::components::verification::{
            compute_citation_hash, verify_evidence, RelocationPolicy,
        };
        use crate::models::VerificationStatus;

        let (dir, paths) = setup();
        fs::write(dir.path().join("cited.txt"), b"whole file\n").unwrap();
        let expected_hash = compute_citation_hash(dir.path(), "cited.txt", None).unwrap();
        add(
            &paths,
            &NoopEmbedder,
            evidence_args(vec![serde_json::json!({
                "kind": "code", "citation_path": "cited.txt"
            })]),
        )
        .unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let evidence = load_test_evidence(&conn);
        let evidence_status: String = conn
            .query_row(
                "SELECT evidence_status FROM entries WHERE id='evidence-test'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(evidence_status, "present");
        assert_eq!(evidence.citation_hash, expected_hash);
        assert_eq!(evidence.citation_sha, config::git_head_sha());
        let result = verify_evidence(&evidence, dir.path(), RelocationPolicy::Never);
        assert_eq!(result.status, VerificationStatus::Verified);

        let evidence_event = ev_mod::read_events(&paths.events).unwrap().events.remove(1);
        assert_eq!(evidence_event["evidence"]["citation_hash"], expected_hash);
        assert_eq!(
            evidence_event["evidence"]["citation_sha"],
            config::git_head_sha().unwrap()
        );
    }

    #[test]
    fn test_kb_core_add_resolves_ranged_citation_path() {
        use crate::components::verification::{
            compute_citation_hash, verify_evidence, RelocationPolicy,
        };
        use crate::models::VerificationStatus;

        let (dir, paths) = setup();
        fs::write(dir.path().join("cited.txt"), b"abcdef").unwrap();
        let expected_hash = compute_citation_hash(dir.path(), "cited.txt", Some((0, 3))).unwrap();
        add(
            &paths,
            &NoopEmbedder,
            evidence_args(vec![serde_json::json!({
                "kind": "code", "citation_path": "cited.txt:0-3"
            })]),
        )
        .unwrap();
        let conn = Connection::open(&paths.db).unwrap();
        let evidence = load_test_evidence(&conn);
        assert_eq!(evidence.citation_hash, expected_hash);
        let result = verify_evidence(&evidence, dir.path(), RelocationPolicy::Never);
        assert_eq!(result.status, VerificationStatus::Verified);
    }

    #[test]
    fn test_kb_core_add_memoizes_duplicate_path_only_hash_resolution() {
        use crate::components::verification::compute_citation_hash;

        CITATION_HASH_RESOLUTION_CALLS.with(|c| c.set(0));

        let (dir, paths) = setup();
        fs::write(dir.path().join("cited.txt"), b"whole file\n").unwrap();
        let expected_hash = compute_citation_hash(dir.path(), "cited.txt", None).unwrap();
        add(
            &paths,
            &NoopEmbedder,
            evidence_args(vec![
                serde_json::json!({"kind": "code", "citation_path": "cited.txt"}),
                serde_json::json!({"kind": "code", "citation_path": "cited.txt"}),
                serde_json::json!({"kind": "code", "citation_path": "cited.txt"}),
            ]),
        )
        .unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let evidence_rows = load_all_test_evidence(&conn);
        assert_eq!(evidence_rows.len(), 3);
        assert!(evidence_rows
            .iter()
            .all(|row| row.citation_hash == expected_hash));
        assert!(evidence_rows
            .iter()
            .all(|row| row.citation_sha == config::git_head_sha()));
        assert_eq!(CITATION_HASH_RESOLUTION_CALLS.with(|c| c.get()), 1);
    }

    #[test]
    fn test_kb_core_add_preserves_explicit_citation_hash() {
        use crate::components::verification::{verify_evidence, RelocationPolicy};
        use crate::models::VerificationStatus;

        let (dir, paths) = setup();
        fs::write(dir.path().join("cited.txt"), b"abcdef").unwrap();
        let explicit = "sha256:not-the-file-hash";
        add(
            &paths,
            &NoopEmbedder,
            evidence_args(vec![serde_json::json!({
                "kind": "code", "citation_path": "cited.txt", "citation_hash": explicit
            })]),
        )
        .unwrap();
        let conn = Connection::open(&paths.db).unwrap();
        let evidence = load_test_evidence(&conn);
        assert_eq!(evidence.citation_hash, explicit);
        let result = verify_evidence(&evidence, dir.path(), RelocationPolicy::Never);
        assert_eq!(result.status, VerificationStatus::Unverified);
    }

    #[test]
    fn test_kb_core_add_missing_citation_file_does_not_append_event() {
        let (_dir, paths) = setup();
        let before = fs::read(&paths.events).unwrap_or_default();
        let err = add(
            &paths,
            &NoopEmbedder,
            evidence_args(vec![serde_json::json!({
                "kind": "code", "citation_path": "missing.txt"
            })]),
        )
        .unwrap_err();
        assert!(err.to_string().contains("missing.txt"), "{err}");
        assert_eq!(fs::read(&paths.events).unwrap_or_default(), before);
    }

    // -------------------------------------------------------------------------
    // FAILING ACCEPTANCE TEST (written pre-implementation per TDD mandate).
    //
    // AC2 (batch atomicity): expire events and upsert land in ONE
    // `append_events_batch` call — NOT a loop of per-event appends.
    //
    // Pre-fix, the call sites in add.rs and mcp.rs use:
    //   for old_id in existing_ids {
    //       append_event(&paths.events, &expire_ev)?;   // ← one append per expire
    //       apply_event(&conn, emb, &expire_ev)?;
    //   }
    //   append_events_batch(&paths.events, &[add_event, ...evidence...])
    //
    // That means N+1 separate JSONL write calls, not 1.  This test verifies
    // that after a `kb_core::add` with replace_path=true the event log contains
    // all events as a SINGLE contiguous block (measurable via line count == 1 +
    // expire_count + evidence_count and ordering verification).
    //
    // Because kb_core::add is the NEW module, this test can only PASS once the
    // implementation below exists.  Before the module existed the test file
    // itself would not compile, proving the "failing first" property.
    // -------------------------------------------------------------------------

    /// AC2: replace_path=true with two pre-existing entries:
    /// All events (2 expire + 1 upsert) appear in the JSONL in the correct order.
    #[test]
    fn test_kb_core_add_batch_atomicity_replace_path() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Seed two existing entries at the same path.
        for seed_id in &["seed-1", "seed-2"] {
            let ev = serde_json::json!({
                "action": "upsert", "table": "entries",
                "id": seed_id, "path": "docs/guide",
                "summary": "old", "content": "old", "tags": [],
                "ts": "2024-01-01T00:00:00Z",
            });
            ev_mod::append_event(&paths.events, &ev).unwrap();
            let conn = db::open_db(&paths.db).unwrap();
            db::apply_event(&conn, &emb, &ev).unwrap();
        }

        // Count lines before.
        let before_lines = ev_mod::read_events(&paths.events).unwrap().events.len();
        assert_eq!(before_lines, 2, "seeded 2 events");

        let args = AddArgs {
            id: "new-1".to_string(),
            path: "docs/guide".to_string(),
            summary: "new guide".to_string(),
            content: "new content".to_string(),
            tags: serde_json::json!([]),
            version_ref: Some("abc".to_string()),
            permanent: false,
            replace_path: true,
            kind: "convention".to_string(),
            evidence_status: "n/a".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: "replaced by --replace-path".to_string(),
            dedup_cutoff: None,
            cues: vec![],
        };

        add(&paths, &emb, args).unwrap();

        let lines = ev_mod::read_events(&paths.events).unwrap().events;

        // 2 seed events + 2 expire + 1 upsert = 5 total events.
        assert_eq!(
            lines.len(),
            5,
            "expected 5 events (2 seed + 2 expire + 1 upsert), got {}",
            lines.len()
        );

        // Events 2 and 3 (0-indexed) must be expire events.
        let ev2 = &lines[2];
        let ev3 = &lines[3];
        let ev4 = &lines[4];
        assert_eq!(ev2["action"], "expire", "event[2] must be expire");
        assert_eq!(ev3["action"], "expire", "event[3] must be expire");
        assert_eq!(ev4["action"], "upsert", "event[4] must be upsert");
        assert_eq!(ev4["id"], "new-1");

        // DB: old entries must be stale, new entry active.
        let conn = Connection::open(&paths.db).unwrap();
        for seed_id in &["seed-1", "seed-2"] {
            let stale: i64 = conn
                .query_row(
                    "SELECT is_stale FROM entries WHERE id=?1",
                    params![seed_id],
                    |r| r.get(0),
                )
                .unwrap();
            assert_eq!(stale, 1, "seed {seed_id} must be stale");
        }
        let new_stale: i64 = conn
            .query_row("SELECT is_stale FROM entries WHERE id='new-1'", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(new_stale, 0, "new entry must be active");
    }

    /// AC1 (signature): kb_core::add does NOT read KB_NO_EMBED from the environment.
    /// The embedder is injected by the caller.
    ///
    /// This test calls kb_core::add with a NoopEmbedder while KB_NO_EMBED is
    /// unset. If the impl read KB_NO_EMBED, it would silently switch embedder
    /// behavior; since we control the embedder here, we can assert the correct
    /// path was taken.
    #[test]
    fn test_kb_core_add_embedder_injected_not_from_env() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Ensure KB_NO_EMBED is not set.
        std::env::remove_var("KB_NO_EMBED");

        let args = AddArgs {
            id: "env-test-1".to_string(),
            path: "src/foo".to_string(),
            summary: "env test".to_string(),
            content: "body".to_string(),
            tags: serde_json::json!(["env"]),
            version_ref: None,
            permanent: false,
            replace_path: false,
            kind: "belief".to_string(),
            evidence_status: "missing".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: String::new(),
            dedup_cutoff: None,
            cues: vec![],
        };

        // Must succeed — the NoopEmbedder is injected and used, not looked up via env.
        add(&paths, &emb, args).unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM entries WHERE id='env-test-1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(count, 1, "entry must exist in DB");
    }

    /// AC4 (drift table): session_id is propagated to the upsert event.
    #[test]
    fn test_kb_core_add_session_id_propagated() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        let args = AddArgs {
            id: "sess-test-1".to_string(),
            path: "src/sess".to_string(),
            summary: "sess test".to_string(),
            content: "body".to_string(),
            tags: serde_json::json!([]),
            version_ref: None,
            permanent: false,
            replace_path: false,
            kind: "convention".to_string(),
            evidence_status: "n/a".to_string(),
            evidence_rows: vec![],
            ts: chrono::Utc::now().to_rfc3339(),
            session: "mcp".to_string(),
            session_id: Some("test-sess-42".to_string()),
            expire_reason: String::new(),
            dedup_cutoff: None,
            cues: vec![],
        };

        add(&paths, &emb, args).unwrap();

        let conn = Connection::open(&paths.db).unwrap();
        let session_id: Option<String> = conn
            .query_row(
                "SELECT session_id FROM entries WHERE id='sess-test-1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(session_id, Some("test-sess-42".to_string()));
    }

    /// AC3 (convergence): test that add.rs::execute_with delegates to kb_core::add
    /// by verifying the same atomicity property holds when called through the CLI
    /// path.  The CLI path goes through `Add::execute_with` which must call
    /// `kb_core::add` after the refactor.
    #[test]
    fn test_add_execute_with_delegates_to_kb_core() {
        use crate::commands::add::Add;

        let dir = tempdir().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join(".state/agent-kb")).unwrap();
        let paths = Paths::from_root(root);
        let emb = NoopEmbedder;

        // Seed an entry at the path.
        let seed_cmd = Add {
            path: "docs/convergence".to_string(),
            summary: "old".to_string(),
            content: "old".to_string(),
            tags: "test".to_string(),
            version_ref: Some("aaa".to_string()),
            id: Some("conv-seed-1".to_string()),
            permanent: false,
            replace_path: false,
            kind: "convention".to_string(),
            evidence: vec![],
            evidence_file: None,
            cues: vec![],
        };
        seed_cmd.execute_with(&paths, &emb).unwrap();

        let before_lines = ev_mod::read_events(&paths.events).unwrap().events.len();

        // Now add with replace_path — all events must land in one batch.
        let cmd = Add {
            path: "docs/convergence".to_string(),
            summary: "new".to_string(),
            content: "new".to_string(),
            tags: "test".to_string(),
            version_ref: Some("bbb".to_string()),
            id: Some("conv-new-1".to_string()),
            permanent: false,
            replace_path: true,
            kind: "convention".to_string(),
            evidence: vec![],
            evidence_file: None,
            cues: vec![],
        };
        cmd.execute_with(&paths, &emb).unwrap();

        let lines = ev_mod::read_events(&paths.events).unwrap().events;

        // before_lines + 1 expire + 1 upsert
        assert_eq!(
            lines.len(),
            before_lines + 2,
            "expected {}, got {}",
            before_lines + 2,
            lines.len()
        );
        // The expire must appear BEFORE the upsert.
        let expire_ev = &lines[before_lines];
        let upsert_ev = &lines[before_lines + 1];
        assert_eq!(expire_ev["action"], "expire");
        assert_eq!(upsert_ev["action"], "upsert");
        assert_eq!(upsert_ev["id"], "conv-new-1");
    }

    /// AC3 (convergence): test that mcp.rs::handle_add delegates to kb_core::add.
    #[test]
    fn test_handle_add_delegates_to_kb_core() {
        use crate::commands::mcp::tests_api::handle_add_for_test;

        let (_dir, paths) = setup();
        let emb = NoopEmbedder;

        // Seed entry via a raw event (bypass handle_add) so we control the state.
        let seed_ev = serde_json::json!({
            "action": "upsert", "table": "entries",
            "id": "mcp-seed-1", "path": "mcp/conv",
            "summary": "old", "content": "old", "tags": [],
            "ts": "2024-01-01T00:00:00Z",
        });
        ev_mod::append_event(&paths.events, &seed_ev).unwrap();
        let conn = db::open_db(&paths.db).unwrap();
        db::apply_event(&conn, &emb, &seed_ev).unwrap();
        drop(conn);

        let before_lines = ev_mod::read_events(&paths.events).unwrap().events.len();

        let id = serde_json::json!("mcp-test");
        let req = serde_json::json!({
            "method": "add", "id": "mcp-test",
            "path": "mcp/conv", "summary": "new", "content": "new",
            "tags": ["a"], "kind": "convention", "replace_path": true,
        });
        let resp = handle_add_for_test(&id, &req, &paths, &emb);
        assert_eq!(resp["type"], "ok", "resp: {resp}");

        let lines = ev_mod::read_events(&paths.events).unwrap().events;
        // before_lines + 1 expire + 1 upsert
        assert_eq!(
            lines.len(),
            before_lines + 2,
            "expected {} lines, got {}",
            before_lines + 2,
            lines.len()
        );
        let expire_ev = &lines[before_lines];
        let upsert_ev = &lines[before_lines + 1];
        assert_eq!(expire_ev["action"], "expire", "expire must come first");
        assert_eq!(upsert_ev["action"], "upsert");
    }

    #[test]
    fn test_kb_core_add_replace_path_propagates_existing_id_decode_failure() {
        let (_dir, paths) = setup();
        let emb = NoopEmbedder;
        let conn = db::open_db(&paths.db).unwrap();
        conn.execute(
            "INSERT INTO entries(
                id, path, summary, content, tags, version_ref, permanent, is_stale,
                kind, evidence_status, session_id, created_at, updated_at
             ) VALUES(CAST(X'00' AS BLOB), ?1, 'old', 'old', '[]', NULL, 0, 0, 'belief', 'n/a', NULL, ?2, ?2)",
            rusqlite::params!["docs/corrupt", "2024-01-01T00:00:00Z"],
        )
        .unwrap();
        drop(conn);

        let args = AddArgs {
            id: "new-corrupt".to_string(),
            path: "docs/corrupt".to_string(),
            summary: "new".to_string(),
            content: "new".to_string(),
            tags: serde_json::json!([]),
            version_ref: None,
            permanent: false,
            replace_path: true,
            kind: "belief".to_string(),
            evidence_status: "n/a".to_string(),
            evidence_rows: vec![],
            ts: "2024-01-01T00:00:00Z".to_string(),
            session: "test".to_string(),
            session_id: None,
            expire_reason: "replace".to_string(),
            dedup_cutoff: None,
            cues: vec![],
        };

        let err = add(&paths, &emb, args).unwrap_err();
        assert!(
            err.to_string().contains("Invalid column type")
                || err.to_string().contains("invalid column type"),
            "expected decode failure, got: {err}"
        );
    }
}
